function HomeScreen({brand,onNavigate}){
const {Sidebar,TopBar,Hero,Section,ActionCard,HistoryItem,KnowledgeCard,ActivityItem,Alert,Card}=window.ATLASDesignSystem_46b296;
const {IconRocket}=window.AtlasUIKit;
return React.createElement(React.Fragment,null,
React.createElement(Sidebar,{activeItem:"Inicio",logoSrc:"../../assets/logo.svg",items:window.AtlasUIKit.navItems("Inicio",onNavigate),footer:React.createElement("div",{style:{display:"flex",flexDirection:"column",gap:10}},
React.createElement("div",{style:{fontSize:12,color:"var(--color-text-muted)",textTransform:"uppercase",letterSpacing:"0.08em"}},"Trabajando en"),
React.createElement("div",{style:{color:"var(--color-text-primary)",fontSize:14,fontWeight:600,marginBottom:10}},brand),
React.createElement("div",{style:{display:"flex",alignItems:"center",gap:10,paddingTop:10,borderTop:"1px solid var(--color-border-subtle)"}},
React.createElement("div",{style:{width:32,height:32,borderRadius:"50%",background:"var(--color-primary)",color:"#fff",display:"flex",alignItems:"center",justifyContent:"center",fontSize:13,fontWeight:600}},"AG"),
React.createElement("div",null,React.createElement("div",{style:{fontSize:13,color:"var(--color-text-primary)"}},"Ana García"),React.createElement("div",{style:{fontSize:11,color:"var(--color-text-muted)"}},"Facilitador"))))}),
React.createElement("div",{style:{flex:1,display:"flex",flexDirection:"column",minWidth:0}},
React.createElement(TopBar,{brand}),
React.createElement("div",{style:{flex:1,padding:32,maxWidth:1180,margin:"0 auto",width:"100%"}},
React.createElement(Hero,{title:"Bienvenido a ATLAS",subtitle:"Tu asistente inteligente de conocimiento empresarial",
description:"Conversa, busca conocimiento y trabaja con total privacidad en el contexto de tu marca.",
visual:React.createElement(IconRocket,{size:100})}),
React.createElement("div",{style:{height:28}}),
React.createElement(Section,{title:"¿Qué quieres hacer hoy?"},
React.createElement("div",{style:{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:16}},
React.createElement(ActionCard,{icon:"💬",tone:"primary",title:"Conversar con ATLAS",description:"Haz preguntas, pide análisis y obtén respuestas útiles.",cta:"Iniciar conversación →",onClick:()=>onNavigate("chat")}),
React.createElement(ActionCard,{icon:"📖",tone:"cyan",title:"Explorar conocimiento",description:"Busca documentos, guías y recursos guardados.",cta:"Buscar conocimiento",onClick:()=>onNavigate("knowledge")}),
React.createElement(ActionCard,{icon:"🏢",tone:"primary",title:"Trabajar con otra marca",description:"Cambia de marca o crea un nuevo contexto.",cta:"Gestionar marcas",onClick:()=>onNavigate("brands")}),
React.createElement(ActionCard,{icon:"📈",tone:"warning",title:"Ver actividad",description:"Revisa la actividad reciente en esta sesión.",cta:"Ver actividad",onClick:()=>onNavigate("activity")}))),
React.createElement("div",{style:{height:12}}),
React.createElement("div",{style:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:24}},
React.createElement(Section,{title:"Continúa donde lo dejaste"},React.createElement(Card,null,
React.createElement(HistoryItem,{question:"¿Qué contratos tengo con Acme?",time:"Hace 15 minutos"}),
React.createElement(HistoryItem,{question:"Dame un resumen de los documentos de RRHH",time:"Hace 1 hora"}),
React.createElement(HistoryItem,{question:"¿Cuáles son las cláusulas más importantes?",time:"Hace 2 horas"}))),
React.createElement(Section,{title:"Ejemplos para empezar"},React.createElement(Card,null,
["¿Qué documentos tengo sobre finanzas?","Resume los puntos clave del manual de ventas","¿Cuáles son mis pendientes importantes?","Explícame este documento en lenguaje simple"].map(q=>
React.createElement("div",{key:q,style:{padding:"10px 4px",fontSize:14,color:"var(--color-cyan)",borderBottom:"1px solid var(--color-border-subtle)",cursor:"pointer"}},q))))),
React.createElement("div",{style:{height:12}}),
React.createElement("div",{style:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:24}},
React.createElement(Section,{title:"Conocimiento destacado"},React.createElement(Card,null,
React.createElement(KnowledgeCard,{title:"Manual de bienvenida",type:"Guía"}),
React.createElement(KnowledgeCard,{title:"Política de gastos",type:"Documento"}),
React.createElement(KnowledgeCard,{title:"Guía de procesos comerciales",type:"Documento"}))),
React.createElement(Section,{title:"Actividad reciente · Esta sesión"},React.createElement(Card,null,
React.createElement(ActivityItem,{icon:"💬",text:'Conversar sobre "¿Qué contratos tengo con Acme?"',time:"Ahora",tone:"primary"}),
React.createElement(ActivityItem,{icon:"🔍",text:'Buscaste "contratos de servicio"',time:"Hace 8 min",tone:"cyan"}),
React.createElement(ActivityItem,{icon:"✎",text:"Corregiste una respuesta de ATLAS",time:"Hace 25 min",tone:"warning"})))),
React.createElement("div",{style:{height:20}}),
React.createElement(Alert,{tone:"info"},"ATLAS trabaja con aislamiento total por marca. Tu información está protegida y no se comparte."))));
}
window.AtlasUIKit=Object.assign(window.AtlasUIKit||{},{HomeScreen});
